name: Build on GitHub and deploy to server

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  deploy:
    # ---- RUNS ON SERVER ----
    runs-on: self-hosted
    # needs: build
    permissions:
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
        # ---- SETUP LOWERCASE OWNER ----
      - name: Get lowercase repository owner
        run: echo "REPO_OWNER_LOWERCASE=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

        # ---- LOGIN TO GHCR ----
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
        # ---- PULL IMAGES ----
      - name: Pull images
        run: |
          docker pull $REGISTRY/${REPO_OWNER_LOWERCASE}/inno_canvas_dashboard-backend:latest
          docker pull $REGISTRY/${REPO_OWNER_LOWERCASE}/inno_canvas_dashboard-frontend:latest

        # ---- START CONTAINERS ----
      - name: Start containers
        run: |
          docker compose -f docker-compose.prod.yml up -d --remove-orphans